# Generated by Django 2.2.4 on 2019-09-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='food_item',
            field=models.TextField(),
        ),
    ]
