# Generated by Django 2.2.4 on 2019-09-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_auto_20190910_2053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
